apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-httpd
  namespace: openshift-gitops
spec:
  destination:
    namespace: httpd
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: deployment
    repoURL: https://github.com/andreaskaris/argo-test.git
    targetRevision: master
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
