apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: httpd
    security.openshift.io/scc.podSecurityLabelSync: "false"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
  name: httpd
