apiVersion: v1
kind: Service
metadata:
  name: httpd
  namespace: httpd
  labels:
    app: httpd
spec:
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
